schema_version: 1

context:
  name: grakel
  version: "0.1.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 36e4e6636b3a5657b820aa1b0d01e5f1f3ff0e13bd5d82449f68d07403f411a4

build:
  number: 1
  skip: match(python, ">=3.13")
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - pip
    - numpy
    - python
    - setuptools
    - cython >=0.27.3
  run:
    - cython >=0.27.3
    - future >=0.16.0
    - joblib
    - nose >=1.1.2
    - numpy >=1.14.0
    - python
    - scikit-learn >=0.19
    - six >=1.11.0

tests:
  - python:
      imports:
        - grakel
        - grakel.datasets
      pip_check: true

about:
  license: BSD-3-Clause
  license_file: LICENSE  # Waiting for License to be included in pip package
  summary: A scikit-learn compatible library for graph kernels
  description: |
    GraKeL is a library that provides implementations of several
    well-established graph kernels. The library unifies these kernels
    into a common framework. Furthermore, it provides implementations of
    some frameworks that work on top of graph kernels. Specifically,
    GraKeL contains 15 kernels and 2 frameworks. The library is compatible
    with the scikit-learn pipeline allowing easy and fast integration
    inside machine learning algorithms.
  homepage: https://ysig.github.io/GraKeL/
  repository: https://github.com/ysig/GraKeL
  documentation: https://ysig.github.io/GraKeL/

extra:
  recipe-maintainers:
    - jan-janssen
